"""Refactor Inicial Decimal e Services

Revision ID: 00a0dda388c8
Revises: 
Create Date: 2025-11-18 19:24:49.884472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a0dda388c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('lead_source', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zip_code', sa.String(length=10), nullable=True),
    sa.Column('main_contact_birthday', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_name'), ['name'], unique=True)

    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('selection_deadline_days', sa.Integer(), nullable=False),
    sa.Column('editing_deadline_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('goal_contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_date', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interaction_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interaction_log_interaction_date'), ['interaction_date'], unique=False)

    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_code', sa.String(length=128), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('selection_completed_date', sa.Date(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('down_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('session_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extra_photos_qty', sa.Integer(), nullable=False),
    sa.Column('extra_photo_unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('printing_qty', sa.Integer(), nullable=False),
    sa.Column('printing_unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('kanban_status', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('session_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['session_type_id'], ['session_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_session_code'), ['session_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_session_session_date'), ['session_date'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('recurrence_id', sa.String(length=50), nullable=True),
    sa.Column('recurrence_installment', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='efetivado', nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_recurrence_id'), ['recurrence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_transaction_type'), ['transaction_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transaction_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_recurrence_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_category'))

    op.drop_table('transaction')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_session_date'))
        batch_op.drop_index(batch_op.f('ix_session_session_code'))

    op.drop_table('session')
    with op.batch_alter_table('interaction_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interaction_log_interaction_date'))

    op.drop_table('interaction_log')
    op.drop_table('goal_contribution')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('session_type')
    op.drop_table('goal')
    op.drop_table('configuration')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_name'))
        batch_op.drop_index(batch_op.f('ix_client_email'))

    op.drop_table('client')
    # ### end Alembic commands ###
